AWSTemplateFormatVersion: '2010-09-09'
Description: Nuxt with aws-lambda test

Resources:
  NuxtLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: nuxt-demo-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  NuxtLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: nuxt-demo-lambda-function
      Handler: index.handler
      Role: !GetAtt NuxtLambdaRole.Arn
      Code: ./lambda.zip
      Runtime: nodejs22.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          NODE_ENV: production
  
  NuxtLambdaPermissionForInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref NuxtLambdaFunction
      Principal: "*"
  
  NuxtLambdaPermissionForUrlInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref NuxtLambdaFunction
      Principal: "*"
      FunctionUrlAuthType: NONE
  
  NuxtLambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt NuxtLambdaFunction.Arn
      AuthType: NONE
      Cors:
        AllowOrigins:
          - '*'
        AllowMethods:
          - '*'
        AllowHeaders:
          - '*'
        MaxAge: 86400  # 24 hours

  NuxtLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NuxtLambdaFunction}
      RetentionInDays: 7

  NuxtDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        DefaultCacheBehavior:
          TargetOriginId: NuxtLambdaOrigin
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: NuxtLambdaOrigin
            DomainName: !Select [2, !Split ["/", !GetAtt NuxtLambdaFunctionUrl.FunctionUrl]]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only

Outputs:
  NuxtDistributionDomainName:
    Description: The CloudFront distribution domain name
    Value: !GetAtt NuxtDistribution.DomainName
